config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path("", include("core.urls", namespace="core"),),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

lists/urls.py
from django.urls import path
from . import views

app_name = "lists"

urlpatterns = [
    path("favs/", views.UserFavsDetail.as_view(), name="detail"),
    path("<int:room_pk>/<str:action>/", views.toggle_fav, name="toggle"),
]

templates/mixins/room_card.html
<div class="w-1/4 mb-6 px-2">
    <a href="{% url "rooms:detail" room.pk %}">
        <div class="w-full h-56 bg-center bg-cover rounded-lg mb-3" style="background-image: url('{{room.first_photo}}')"></div>
        <div>
            <div class="flex mb-2 items-center">
                {% if room.host.superhost %}
                <span class="uppercase border-2 rounded-md border-black font-semibold text-xs px-2 mr-2">superhost</span>
                {% endif %}
                <span class="text-xs text-gray-600 truncate block w-11/12 mr-1">{{room.country.name}} {{room.city}}</span>
                <i class="fas fa-star fa-xs text-red-500 mr-1"></i>
                <span class="text-xs font-semibold">{{room.total_average}}</span>
            </div>
            <div class="truncate block w-11/12 text-black text-sm font-medium">
            {{room.name}}
            </div>
        </div>
    </a>    
</div>

templates/mixins/user_avatar.html
{% if user.avatar %}
    <div class="{{h_w|default:'h-20 w-20'}} bg-cover bg-center rounded-full" style="background-image: url({{user.avatar_thumbnail.url}});">
{% else %}
    <div class="{{h_w|default:'h-20 w-20'}} bg-gray-700 rounded-full text-white {{text|default:'text-3xl'}} flex items-center justify-center">
        {{user.first_name|first}}
{% endif %}
</div>