config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path("", include("core.urls", namespace="core"),),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

lists/urls.py
from django.urls import path
from . import views

app_name = "lists"

urlpatterns = [
    path("favs/", views.UserFavsDetail.as_view(), name="detail"),
    path("<int:room_pk>/<str:action>/", views.toggle_fav, name="toggle"),
]

reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"


urlpatterns = [
    path("<int:room_pk>/create/", views.create_review, name="create"),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("add/", views.CreateRoomView.as_view(), name="add"),
    path("<int:pk>/", views.RoomView.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/delete/", views.delete_room, name="delete-room"),
    path("<int:pk>/photos/", views.EditPhotoView.as_view(), name="photos"),
    path("<int:pk>/photos/add/", views.UploadPhotoView.as_view(), name="upload-photo"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="delete-photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.UpdatePhotoView.as_view(),
        name="update-photo",
    ),
    path("search/", views.SearchView.as_view(), name="search"),
]

rooms/models.py
from django.db import models
from django_countries.fields import CountryField
from django.urls import reverse
from django.utils import timezone
from core import models as core_models
from users import models as users_models
from cal import Calendar


class AbstractItem(models.Model):

    """ AbstractItem Model Definition """

    name = models.CharField(max_length=80)

    class meta:
        abstract = True

    def __str__(self):
        return self.name


class RoomType(AbstractItem):

    """ RoomType Model Definition """

    class Meta:
        verbose_name = "Room Type"


class Amenity(AbstractItem):

    """ Amenity Model Definition """

    class Meta:
        verbose_name_plural = "Amenities"


class Facility(AbstractItem):

    """ Facility Model Definition """

    class Meta:
        verbose_name_plural = "Facilities"


class HouseRule(AbstractItem):

    """ HouseRule Model Definition """

    class Meta:
        verbose_name = "House Rule"


class Photo(models.Model):

    """ Photo Model Definition """

    caption = models.CharField(max_length=80)
    file = models.ImageField(upload_to="rooms_photo")
    room = models.ForeignKey("Room", related_name="photos", on_delete=models.CASCADE)

    def __str__(self):
        return self.caption


class Room(core_models.TimeStampedModel):

    """ Room Model Definition """

    name = models.CharField(max_length=140)
    description = models.TextField()
    country = CountryField()
    city = models.CharField(max_length=80)
    price = models.IntegerField()
    address = models.CharField(max_length=140)
    guests = models.IntegerField()
    beds = models.IntegerField()
    bedrooms = models.IntegerField()
    bath = models.IntegerField()
    check_in = models.TimeField()
    check_out = models.TimeField()
    instant_book = models.BooleanField(default=False)
    host = models.ForeignKey(
        users_models.User, related_name="rooms", on_delete=models.CASCADE
    )
    room_type = models.ForeignKey(
        RoomType, related_name="rooms", on_delete=models.SET_NULL, null=True
    )
    amenity = models.ManyToManyField(Amenity, related_name="rooms", blank=True)
    facility = models.ManyToManyField(Facility, related_name="rooms", blank=True)
    house_rule = models.ManyToManyField(HouseRule, related_name="rooms", blank=True)

    def __str__(self):
        return self.name

    def total_average(self):
        reviews = self.reviews.all()
        ratings = 0
        for review in reviews:
            ratings += review.review_average()
        if ratings == 0:
            return 0
        else:
            return round(ratings / len(reviews), 2)

    def save(self, *args, **kwargs):
        self.city = str.capitalize(self.city)
        super(Room, self).save(*args, **kwargs)  # Call the real save() method

    def get_absolute_url(self):
        return reverse("rooms:detail", kwargs={"pk": self.pk})

    def first_photo(self):
        try:
            (photo,) = self.photos.all()[:1]
            return photo.file.url
        except ValueError:
            return None

    def get_four_photos(self):
        photos = self.photos.all()[1:5]
        return photos

    def get_calendar(self):
        now = timezone.now()
        this_month = Calendar(now.year, now.month)
        next_year = now.year
        next_month = now.month + 1
        if now.month == 12:
            next_year += 1
            next_month = 1

        next_month = Calendar(next_year, next_month)
        return [this_month, next_month]

rooms/forms.py
from django import forms
from django_countries.fields import CountryField
from . import models


class SearchForm(forms.Form):

    city = forms.CharField(required=False)
    country = CountryField().formfield(initial="KR")
    price = forms.IntegerField(required=False)
    guests = forms.IntegerField(required=False)
    beds = forms.IntegerField(required=False)
    bedrooms = forms.IntegerField(required=False)
    baths = forms.IntegerField(required=False)
    room_type = forms.ModelChoiceField(
        models.RoomType.objects.all(), empty_label="Any Kind", required=False
    )
    instant_book = forms.BooleanField(required=False)
    superhost = forms.BooleanField(required=False)
    amenities = forms.ModelMultipleChoiceField(
        models.Amenity.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )
    facilities = forms.ModelMultipleChoiceField(
        models.Facility.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )


class CreatePhotoForm(forms.ModelForm):
    class Meta:
        model = models.Photo
        fields = (
            "caption",
            "file",
        )

    def save(self, pk, *args, **kwargs):
        photo = super().save(commit=False)
        room = models.Room.objects.get(pk=pk)
        photo.room = room
        photo.save()


class CreateRoomForm(forms.ModelForm):
    class Meta:
        model = models.Room
        fields = (
            "name",
            "description",
            "country",
            "city",
            "price",
            "address",
            "guests",
            "beds",
            "bedrooms",
            "bath",
            "check_in",
            "check_out",
            "instant_book",
            "room_type",
            "amenity",
            "facility",
            "house_rule",
        )

    def save(self, *args, **kwargs):
        room = super().save(commit=False)

        return room

rooms/views.py
from django.http import Http404
from django.views.generic import ListView, DetailView, View, UpdateView, FormView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.http import Http404
from django.shortcuts import render, redirect, reverse
from django.contrib import messages
from django_countries import countries
from . import models, forms
from users import mixins as user_mixins

"""
def all_rooms(request):

    # pagination (without django func)
    
    page = int(request.GET.get("page", 1))
    page_size = 10
    limit = page_size * page
    offset = limit - page_size
    all_rooms = models.Room.objects.all()[offset:limit]
    page_count = ceil(models.Room.objects.count() / page_size)

    return render(
        request,
        "rooms/home.html",
        context={
            "room_list": all_rooms,
            "page": page,
            "page_count": page_count,
            "page_range": range(1, page_count+1),
        },
    ) 
    

    # pagination (using django paginator)
    page = int(request.GET.get("page", 1))
    room_list = models.Room.objects.all()
    paginator = Paginator(room_list, 10, orphans=5)

    try:
        rooms = paginator.page(page)
        return render(request, "rooms/home.html", {"page": rooms})
    except EmptyPage:
        return redirect("/")
"""


class HomeView(ListView):

    model = models.Room
    paginate_by = 12
    paginate_orphans = 5
    context_object_name = "rooms"
    ordering = "created"

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        paginator = context["paginator"]
        page_numbers_range = 5  # Display only 5 page numbers
        max_index = len(paginator.page_range)

        page = self.request.GET.get("page")
        current_page = int(page) if page else 1

        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index

        context["has_next"] = False
        if end_index + 1 <= max_index:
            context["has_next"] = True
            context["next"] = end_index + 1

        context["has_previous"] = False
        if start_index != 0:
            context["has_previous"] = True
            context["previous"] = start_index

        page_range = paginator.page_range[start_index:end_index]
        context["page_range"] = page_range
        return context


class RoomView(DetailView):

    model = models.Room


class SearchView(View):
    def get(self, request):
        country = request.GET.get("country")

        if country:

            form = forms.SearchForm(request.GET)

            if form.is_valid():
                country = form.cleaned_data.get("country")
                city = form.cleaned_data.get("city")
                price = form.cleaned_data.get("price")
                guests = form.cleaned_data.get("guests")
                beds = form.cleaned_data.get("beds")
                bedrooms = form.cleaned_data.get("bedrooms")
                baths = form.cleaned_data.get("baths")
                instant_book = form.cleaned_data.get("instant_book")
                superhost = form.cleaned_data.get("superhost")
                room_type = form.cleaned_data.get("room_type")
                amenities = form.cleaned_data.get("amenities")
                facilities = form.cleaned_data.get("facilities")

                filter_args = {}

                if city != "Anywhere":
                    filter_args["city__startswith"] = city

                filter_args["country"] = country

                if price is not None:
                    filter_args["room_type"] = room_type

                if price is not None:
                    filter_args["price__lte"] = price

                if beds is not None:
                    filter_args["beds__gte"] = beds

                if bedrooms is not None:
                    filter_args["bedrooms__gte"] = bedrooms

                if guests is not None:
                    filter_args["guests__gte"] = guests

                if baths is not None:
                    filter_args["bath__gte"] = baths

                for a in amenities:
                    filter_args["amenity"] = a

                for f in facilities:
                    filter_args["facility"] = f

                if instant_book is True:
                    filter_args["instant_book"] = instant_book

                if superhost is True:
                    filter_args["host__superhost"] = superhost

                rooms = models.Room.objects.filter(**filter_args)

                return render(
                    request, "rooms/search.html", {"form": form, "rooms": rooms}
                )
        else:
            form = forms.SearchForm()

        return render(request, "rooms/search.html", {"form": form})


class EditRoomView(user_mixins.LoggedInOnlyView, SuccessMessageMixin, UpdateView):

    model = models.Room
    fields = (
        "name",
        "description",
        "country",
        "city",
        "price",
        "address",
        "guests",
        "beds",
        "bedrooms",
        "bath",
        "check_in",
        "check_out",
        "instant_book",
        "room_type",
        "amenity",
        "facility",
        "house_rule",
    )
    template_name = "rooms/room_edit.html"
    success_message = "Room Updated"

    def get_object(self, queryset=None):

        room = super().get_object(queryset=queryset)

        if room.host.pk != self.request.user.pk:
            raise Http404()
        else:
            return room


class EditPhotoView(user_mixins.LoggedInOnlyView, DetailView):

    model = models.Room
    template_name = "rooms/room_photos.html"

    def get_object(self, queryset=None):

        room = super().get_object(queryset=queryset)

        if room.host.pk != self.request.user.pk:
            raise Http404()
        else:
            return room


@login_required
def delete_photo(request, room_pk, photo_pk):

    user = request.user

    try:
        room = models.Room.objects.get(pk=room_pk)
        if room.host.pk != user.pk:
            messages.error(request, "Permission denied")
        else:
            room.photos.filter(pk=photo_pk).delete()
            messages.success(request, "Photo Deleted")
    except models.Room.DoesNotExist:
        return redirect(reverse("core:home"))

    return redirect(reverse("rooms:photos", kwargs={"pk": room_pk}))


class UpdatePhotoView(user_mixins.LoggedInOnlyView, SuccessMessageMixin, UpdateView):

    model = models.Photo
    fields = ("caption",)
    success_message = "Photo Updated"
    pk_url_kwarg = "photo_pk"
    template_name = "rooms/photo_edit.html"

    def get_success_url(self):

        room_pk = self.kwargs.get("room_pk")

        return reverse("rooms:photos", kwargs={"pk": room_pk})


class UploadPhotoView(user_mixins.LoggedInOnlyView, FormView):

    form_class = forms.CreatePhotoForm
    template_name = "rooms/photo_upload.html"

    def form_valid(self, form):
        pk = self.kwargs.get("pk")
        form.save(pk)
        messages.success(request, "Photo Uploaded")

        return redirect(reverse("rooms:photos", kwargs={"pk": pk}))


class CreateRoomView(user_mixins.LoggedInOnlyView, SuccessMessageMixin, FormView):

    form_class = forms.CreateRoomForm
    template_name = "rooms/room_create.html"
    success_message = "Room Created"

    def form_valid(self, form):
        user = self.request.user
        room = form.save()
        room.host = user
        room.save()
        form.save_m2m()

        return redirect(reverse("rooms:detail", kwargs={"pk": room.pk}))


@login_required
def delete_room(request, pk):

    try:
        room = models.Room.objects.get(pk=pk)
        if room.host.pk != request.user.pk:
            messages.error(request, "Permission denied")
        else:
            models.Room.objects.get(pk=pk).delete()
    except models.Room.DoesNotExist:
        messages.error(request, "Room does not exist")
        return redirect(reverse("core:home"))

    messages.success(request, "Room deleted")
    return redirect(reverse("core:home"))

templates/rooms/detail.html
{% extends "base.html" %}

{% block title_name %}
Home
{% endblock title_name %}

{% block content %}

<div>
    <h1>{{room.name}}</h1>
    <h3>{{room.description}}</h3>
</div>
<div>
    {% if room.host.superhost %}
    <h4>superhost</h4>
    {% endif %}
</div>
<div>
    <h3>Amenities</h3>
    <ul>
        {% for a in room.amenity.all %}
        <li>{{a}}</li>
        {% endfor %}
    </ul>
    <h3>Factilities</h3>
    <ul>
        {% for f in room.facility.all %}
        <li>{{f}}</li>
        {% endfor %}
    </ul>
    <h3>House Rules</h3>
    <ul>
        {% for r in room.house_rule.all %}
        <li>{{r}}</li>
        {% endfor %}
    </ul>
</div>


{% endblock content %}

templates/rooms/photo_edit.html
{% extends "base.html" %}

{% block title_name %}
Edit Photo
{% endblock title_name %}

{% block search_block %}
{% endblock search_block %}

{% block content %}

<div class="form_style container xl:w-1/3 sm:w-7/12 md:w-1/2 lg:w-2/5">

    {% include "mixins/room/room_form.html" with form=form cta="Update Photo" %}

</div>

{% endblock content %}

templates/rooms/photo_upload.html
{% extends "base.html" %}

{% block title_name %}
Upload Room
{% endblock title_name %}

{% block search_block %}
{% endblock search_block %}

{% block content %}

<div class="form_style container xl:w-1/3 sm:w-7/12 md:w-1/2 lg:w-2/5">

    {% include "mixins/room/room_form.html" with form=form cta="Upload Photo" %}

</div>

{% endblock content %}

templates/rooms/room_create.html
{% extends "base.html" %}

{% block title_name %}
Create Room
{% endblock title_name %}

{% block search_block %}
{% endblock search_block %}

{% block content %}

<div class="form_style container xl:w-1/3 sm:w-7/12 md:w-1/2 lg:w-2/5">

    {% include "mixins/room/room_form.html" with form=form cta="Create Room" %}

</div>

{% endblock content %}

templates/rooms/room_detail.html
{% extends "base.html" %}
{% load is_booked i18n on_favs %}

{% block title_name %}
{{room.name}}
{% endblock title_name %}

{% block content %}

<div class="flex mb-16 -mt-16">
    <div class="w-1/2 h-75vh border border-gray-700 bg-center bg-cover" style="background-image: url({{room.first_photo}})"></div>
    <div class="w-1/2 h-75vh flex flex-wrap">
        {% for photo in room.get_four_photos %}
            <div class="border border-gray-700 bg-center bg-cover w-1/2 h-1/2" style="background-image: url({{photo.file.url}})"></div>
        {% endfor %}
    </div>
</div>

<div class="container mx-auto flex justify-around">
    <div class="w-1/2">
        <div class="flex items-center border-section">
            <div class="w-3/4">
                <div class="font-semibold text-2xl mb-1">{{room.name}}</div>
                <div class="text-gray-600 text-sm mb-1">{{room.city}}</div>
                <div>
                    <span class="mr-2">{{room.room_type}}</span>
                    <span class="mr-2">{{room.beds}} bed{{room.beds|pluralize}}</span>
                    <span class="mr-2">{{room.bedrooms}} bedroom{{room.bedrooms|pluralize}}</span>
                    <span class="mr-2">{{room.bath}} bath{{room.bath|pluralize}}</span>
                    <span>{{room.guests}} guest{{room.guests|pluralize}}</span>
                </div>
                {% on_favs room as on_favs_boolean %}
                <div class="my-1 font-semibold text-teal-500 text-sm">
                    {% if on_favs_boolean %}
                        <a href="{% url 'lists:toggle' room.pk 'remove' %}">Remove from Favorites</a>
                    {% else %}
                        <a href="{% url 'lists:toggle' room.pk 'add' %}">Add to Favorites</a>
                    {% endif %}
                </div>
            </div>
            <div class="w-1/4 flex flex-col items-center justify-center">
                <a href="{{room.host.get_absolute_url}}">{% include "mixins/user_avatar.html" with user=room.host %}</a>
                <div class="text-center mt-3">{{room.host.first_name}}</div>
            </div>
        </div>
        <div class="border-section">
            <p>
            {{room.description}}
            </p>
        </div>
        <div class="border-section">
            <div class="mb-5 text-xl font-semibold">Amenities</div>
            <div>
            {% if room.amenity.count == 0 %}
                <div class="text-center text-gray-600">No amenities</div>
            {% endif %}
            {% for a in room.amenity.all %}
                <li>{{a}}</li>
            {% endfor %}
            </div>
        </div>
        <div class="border-section">
            <div class="mb-5 text-xl font-semibold">Facilities</div>
            <div>
            {% if room.facility.count == 0 %}
                <div class="text-center text-gray-600">No facilities</div>
            {% endif %}
            {% for f in room.facility.all %}
                <li>{{f}}</li>
            {% endfor %}
            </div>
        </div>
        <div class="border-section">
            <div class="mb-5 text-xl font-semibold">House Rules</div>
            <div>
            {% if room.house_rule.count == 0 %}
                <div class="text-center text-gray-600">No house rules</div>
            {% endif %}
            {% for h in room.house_rule.all %}
                <li>{{h}}</li>
            {% endfor %}
            </div>
        </div>
        <div>
            <div class="my-8 text-2xl font-semibold">Reviews</div>
            {% if room.reviews.count == 0 %}
                <div class="text-center text-gray-600">No reviews</div>
            {% else %}
                <div class="mb-8 flex items-center">
                    <div>
                        <i class="fas fa-star text-teal-600"></i>
                        <span class="text-lg font-semibold">{{room.total_average}}</span>
                    </div>
                    <div class="h-4 w-px bg-gray-400 mx-5"></div>
                    <div>
                        <span class="text-lg font-semibold">{{room.reviews.count}}</span>
                        <span>review{{room.reviews.count|pluralize}}</span>
                    </div>
                </div>
            {% endif %}
           
            {% for review in room.reviews.all %}
                <div class="border-section">
                    <div class="flex items-center mb-3">
                        <a href="{{review.user.get_absolute_url}}">{% include "mixins/user_avatar.html" with user=review.user h_w='h-10 w-10' text='text-xl' %}</a>
                        <div class="ml-4">
                            <div class="font-semibold">{{review.user.first_name}}</div>
                            <div class="text-sm text-gray-500">{{review.created|date:'F Y'}}</div>
                        </div>
                    </div>
                    <div>{{review.content}}</div>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="w-1/4">
        {% if room.host == user %}
            <a href="{% url 'rooms:edit' room.pk %}" class="btn--small bg-teal-500 text-white">Edit Room</a>
            <a href="{% url 'rooms:delete-room' room.pk %}" class="btn--small bg-red-600 text-white">Delete Room</a>
        {% else %}
            {% if not request.session.is_hosting %}
                {% for cal in room.get_calendar %}
                    <div class="w-full mb-8 font-semibold text-center text-lg">{{cal.year}} / {{cal.get_month}}</div>
                    <div class="mb-8 cal-grid">
                        {% for day_name in cal.day_names %}
                            <span class="mb-2 text-center font-semibold">{{day_name}}</span>
                        {% endfor %}
                        {% for d in cal.get_days %}
                            {% if d.day != 0 %}
                                {% if not d.past %}
                                    {% is_booked room d as is_booked_bool %}
                                    {% if is_booked_bool %}
                                        <span class="flex items-center justify-center bg-teal-200 text-gray-500 rounded p-1 text-sm cursor-default">{{d.day}}</span>
                                    {% else %}
                                        <a href="{% url 'reservations:create' room.pk d.year d.month d.day %}" class="flex items-center justify-center bg-gray-200 rounded p-1 text-sm hover:bg-teal-500 hover:text-white cursor-pointer hover:font-medium">{{d.day}}</a>
                                    {% endif %}
                                {% else %}
                                <span class="flex items-center justify-center bg-red-200 text-gray-500 rounded p-1 text-sm cursor-default">{{d.day}}</span>
                                {% endif %}
                            {% else %}
                                <span></span>
                            {% endif %}
                        {% endfor %}
                    </div>
                {% endfor %}
            {% endif %}
        {% endif %}
    </div>
</div>

{% endblock content %}

templates/rooms/room_edit.html
{% extends "base.html" %}

{% block title_name %}
Edit Room
{% endblock title_name %}

{% block search_block %}
{% endblock search_block %}

{% block content %}

<div class="form_style container xl:w-1/3 sm:w-7/12 md:w-1/2 lg:w-2/5">

    {% include "mixins/room/room_form.html" with form=form cta="Update Room" %}

    <div class="w-full flex items-center justify-center px-6 pt-6">
        <a href="{% url 'rooms:photos' room.pk %}" class="text-teal-500 font-semibold">Edit Photos</a>
    </div>

</div>

{% endblock content %}

templates/rooms/room_list.html
{% extends "base.html" %}
{% load static %}

{% block title_name %}
Home
{% endblock title_name %}

{% block content %}

<div class="container mx-auto w-3/4 mb-10">

    <div class="-mx-10 bg-gray-500 h-50vh mb-20 rounded-lg bg-cover bg-bottom" style="background-image: url({% static 'img/main.jpg' %})"></div>

    <div class="flex flex-wrap -mx-10">
    {% for room in rooms  %}
        {% include "mixins/room_card.html" with room=room %}
    {% endfor %}
    </div>
</div>

<div class="container mx-auto text-center">
    {% if has_previous %}
    <a href="?page={{previous}}">
        <i class="fas fa-arrow-left fa-lg text-teal-500"></i>
    </a>
    {% endif %}

    <span class="mx-2 text-lg">
        {% for page in page_range %}
            {% if page == page_obj.number %}
            <a href="?page={{page}}" class="mx-1 font-semibold">{{page}}</a>
            {% else %}
            <a href="?page={{page}}" class="mx-1">{{page}}</a>
            {% endif %}
        {% endfor %}
    </span>

    {% if has_next %}
    <a href="?page={{next}}">
        <i class="fas fa-arrow-right fa-lg text-teal-500"></i>
    </a>
    {% endif %}
</div>

{% endblock content %}

templates/rooms/room_photos.html
{% extends "base.html" %}

{% block title_name %}
Edit Photos
{% endblock title_name %}

{% block search_block %}
{% endblock search_block %}

{% block content %}

<div class="w-1/2 mb-5 mx-auto">
    <a href="{% url 'rooms:upload-photo' room.pk %}" class="btn--small bg-red-500 text-white w-1/4">Upload Photo</a>
</div>
{% for photo in room.photos.all %}
    <div class="form_style container flex mb-5 w-2/3 justify-between">
        <div class="flex items-center">
            <div class="w-32 h-32 bg-center bg-cover mr-5" style="background-image: url({{photo.file.url}})"></div>
            <div>{{photo.caption}}</div>
        </div>
        <div class="w-1/5">
            <a href="{% url 'rooms:update-photo' room.pk photo.pk %}" class="btn--small bg-teal-500 text-white">Update Photo</a>
            <a href="{% url 'rooms:delete-photo' room.pk photo.pk %}" class="btn--small bg-red-600 text-white">Delete Photo</a>
        </div>
    </div>
{% endfor %}
<div class="w-full flex justify-center my-8">
    <a href="{% url 'rooms:edit' room.pk %}" class="text-teal-500 font-medium text-lg">Back to edit room</a>
</div>

{% endblock content %}

templates/rooms/search.html
{% extends "base.html" %}

{% block title_name %}
Search
{% endblock title_name %}

{% block search_block %}
{% endblock search_block %}

{% block content %}
<h1>Search</h1>

<form action="{% url "rooms:search" %}" method="GET">
    {{form.as_p}}
    <button>Search</button>
</form>

<div>
    <h3>Results</h3>
    {% for room in rooms %}
    <h4>{{room.name}}</h4>
    {% endfor %}
</div>

{% endblock content %}