config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path("", include("core.urls", namespace="core"),),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

conversations/urls.py
from django.urls import path
from . import views

app_name = "conversations"

urlpatterns = [
    path("go/<int:h_pk>/<int:g_pk>/", views.go_conversation, name="go"),
    path("<int:pk>/", views.ConversationDetailView.as_view(), name="detail"),
]

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

reservations/urls.py
from django.urls import path
from . import views

app_name = "reservations"

urlpatterns = [
    path(
        "<int:room_pk>/<int:year>-<int:month>-<int:day>/create/",
        views.create,
        name="create",
    ),
    path("<int:pk>/", views.ReservationDetailView.as_view(), name="detail"),
    path("<int:pk>/<str:verb>/", views.edit_reservation, name="edit"),
]

reservations/models.py
from datetime import timedelta
from django.db import models
from django.utils import timezone
from core import models as core_models


class BookedDay(core_models.TimeStampedModel):
    day = models.DateField()
    reserve = models.ForeignKey("Reservation", on_delete=models.CASCADE)


class Reservation(core_models.TimeStampedModel):

    """ Reservation Model Definition """

    class Meta:
        ordering = [
            "-created",
        ]

    STATUS_PENDING = "pending"
    STATUS_CONFIRMED = "confirmed"
    STATUS_CANCELED = "canceled"

    STATUS_CHOICES = (
        (STATUS_PENDING, "Pending"),
        (STATUS_CONFIRMED, "Confirmed"),
        (STATUS_CANCELED, "Canceled"),
    )

    status = models.CharField(
        max_length=12, choices=STATUS_CHOICES, default=STATUS_PENDING
    )
    check_in = models.DateField()
    check_out = models.DateField()
    guest = models.ForeignKey(
        "users.User", related_name="reservations", on_delete=models.CASCADE
    )
    room_info = models.ForeignKey(
        "rooms.Room", related_name="reservations", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.room_info.name

    def in_progress(self):
        now = timezone.now().date()
        return now >= self.check_in and now <= self.check_out

    in_progress.boolean = True

    def is_finished(self):
        now = timezone.now().date()
        is_finished = now > self.check_out
        if is_finished:
            BookedDay.objects.filter(reserve=self).delete()

        return is_finished

    is_finished.boolean = True

    def save(self, *args, **kwargs):
        if self.pk is None:
            start = self.check_in
            end = self.check_out
            diff = end - start
            existing_booked_days = BookedDay.objects.filter(
                day__range=(start, end)
            ).exists()
            if not existing_booked_days:
                super(Reservation, self).save(*args, **kwargs)
                for d in range(0, diff.days + 1):
                    day = self.check_in + timedelta(days=d)
                    BookedDay.objects.create(day=day, reserve=self)
                return
        else:
            return super(Reservation, self).save(*args, **kwargs)

reservations/views.py
import datetime
from django.http import Http404
from django.shortcuts import render, redirect, reverse
from django.views import View
from django.contrib import messages
from . import models as reservation_models
from rooms import models as room_models
from users import mixins as user_mixins
from . import models
from reviews import forms as review_forms


def create(request, room_pk, year, month, day):

    # reservation pk로 찾아서 생성 후 context로
    reservation = reservation_models.Reservation.objects.get_or_none(pk=room_pk)
    if reservation is None:
        check_in = datetime.datetime(year, month, day)
        check_out = check_in + datetime.timedelta(days=1)
        room = room_models.Room.objects.get_or_none(pk=room_pk)
        if room is not None:
            new_reservation = reservation_models.Reservation.objects.create(
                status="pending",
                check_in=check_in,
                check_out=check_out,
                guest=request.user,
                room_info=room,
            )
            return redirect(
                reverse("reservations:detail", kwargs={"pk": new_reservation.pk})
            )
        else:
            messages.error(request, "Room does not exists")
            return redirect(reverse("core:home"))
    else:
        messages.error(request, "Reservation already exists")
        return redirect(reverse("rooms:detail", kwargs={"pk": room_pk}))


class ReservationDetailView(user_mixins.LoggedInOnlyView, View):
    def get(self, request, *args, **kwargs):

        pk = kwargs.get("pk")
        reservation = reservation_models.Reservation.objects.get_or_none(pk=pk)
        if reservation is None or (
            reservation.guest != request.user
            and reservation.room_info.host != request.user
        ):
            raise Http404()
        form = review_forms.CreateReviewForm()
        return render(
            request,
            "reservations/reservation_detail.html",
            context={"reservation": reservation, "form": form},
        )


def edit_reservation(request, pk, verb):

    reservation = reservation_models.Reservation.objects.get_or_none(pk=pk)
    if reservation is None or (
        reservation.guest != request.user and reservation.room_info.host != request.user
    ):
        raise Http404()

    if verb == "cancel":
        reservation.status = models.Reservation.STATUS_CANCELED
        models.BookedDay.objects.filter(reserve=reservation).delete()
    elif verb == "confirm":
        reservation.status = models.Reservation.STATUS_CONFIRMED
    reservation.save()
    messages.success(request, "Reservation Updated")

    return redirect(reverse("reservations:detail", kwargs={"pk": pk}))

templates/reservations/reservation_detail.html
{% extends "base.html" %}

{% block title_name %}
Reservation Detail
{% endblock title_name %}

{% block search_block %}
{% endblock search_block %}

{% block content %}

<div class="form_style container flex flex-col mb-5 w-2/3 p-0">
    <div class="bg-cover bg-center h-56" style="background-image: url({{reservation.room_info.first_photo}})"></div>
    <div class="font-semibold text-sm border-b py-8 px-5 w-full border-gray-600">{{reservation.check_in}} - {{reservation.check_out}} 
        <span class="ml-5 {% if reservation.status == 'pending' %}text-yellow-600{% endif %}{% if reservation.status == 'canceled' %}text-red-600{% endif %}{% if reservation.status == 'confirmed' %}text-teal-600{% endif %}">{{reservation.get_status_display}}</span>
    </div>
    <div class="py-8 px-5 font-medium text-lg border-b border-gray-600">{{reservation.room_info.name}}</div>
    <div class="flex items-center py-8 border-b border-gray-600">
        <div class="flex flex-col mx-5">
            <a href="{{room.host.get_absolute_url}}">{% include "mixins/user_avatar.html" with user=reservation.room_info.host %}</a>
            <div class="text-center mt-3">{{reservation.room_info.host.first_name}}</div>
        </div>
        <div class="flex flex-col">
            <div class="font-semibold">Contact your Airbnb Host</div>
            <a href="{% url 'conversations:go' reservation.room_info.host.pk reservation.guest.pk %}" class="font-semibold text-teal-500">Send a Message</a>
        </div>
    </div>
    {% if reservation.status == 'pending' %}
    <div class="py-6 px-5">
        <a href="{% url 'reservations:edit' reservation.pk 'cancel' %}" class="btn--small bg-red-500 text-white w-1/5">Cancel Reservation</a>
        {% if reservation.room_info.host == user %}
            <a href="{% url 'reservations:edit' reservation.pk 'confirm' %}" class="mt-3 btn--small bg-teal-500 text-white w-1/5">Confirm Reservation</a>
        {% endif %}
    </div>
    {% endif %}
    {% if reservation.status == 'confirmed' and reservation.is_finished %}
        {% if reservation.guest == user %}
            <div class="w-1/2 mx-auto">
                <span class="my-5 font-semibold text-xl text-center block">Write your review</span>
                <form action="{% url 'reviews:create' reservation.room_info.pk %}" method="POST" class="mb-5">
                    {% csrf_token %}
                    {{form}}
                    <div class="flex justify-center">
                        <button class="btn--small bg-teal-500 my-2 text-white w-1/4 text-sm">Submit Review</button>
                    </div>
                </form>
            </div>
        {% endif %}
    {% endif %}
</div>

{% endblock content %}