config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path("", include("core.urls", namespace="core"),),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

lists/urls.py
from django.urls import path
from . import views

app_name = "lists"

urlpatterns = [
    path("favs/", views.UserFavsDetail.as_view(), name="detail"),
    path("<int:room_pk>/<str:action>/", views.toggle_fav, name="toggle"),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("add/", views.CreateRoomView.as_view(), name="add"),
    path("<int:pk>/", views.RoomView.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/delete/", views.delete_room, name="delete-room"),
    path("<int:pk>/photos/", views.EditPhotoView.as_view(), name="photos"),
    path("<int:pk>/photos/add/", views.UploadPhotoView.as_view(), name="upload-photo"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="delete-photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.UpdatePhotoView.as_view(),
        name="update-photo",
    ),
    path("search/", views.SearchView.as_view(), name="search"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    path("login/github/callback/", views.github_callback, name="github-callback"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao-callback"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "verify/<str:secret>/",
        views.complete_verification,
        name="complete_verification",
    ),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update-profile"),
    path(
        "update-password/", views.UpdatePasswordView.as_view(), name="update-password"
    ),
    path("is-hosting/", views.switch_hosting, name="is-hosting"),
    path("switch-lang/", views.switch_lang, name="switch-lang"),
    path("reservations/", views.UserReservationListView.as_view(), name="reservations"),
    path("sentry-debug/", trigger_error),
]

templates/partial/divider.html
<div class="flex w-full items-center mb-3 mt-1">
    <div class="h-1 border-b border-gray-500 w-1/2"></div>
    <span class="px-2 font-semibold text-gray-600">or</span>
    <div class="h-1 border-b border-gray-500 w-1/2"></div>
</div>

templates/partial/footer.html
{% load i18n %}

<footer class="mt-32 py-20 container mx-auto text-center text-gray-600 border-t border-gray-500">
    <div class="flex flex-col">
        <span class="text-sm">{% trans "2020-08-06 업데이트" %}</span>
        <span class="mb-3">&copy; 2020 Youngs-log. All rights reserved.</span>
        {% get_current_language as LANGUAGE_CODE %}
        <select class="w-1/12 mx-auto py-1 text-xs" id="js-lang"">
            <option value="en" 
                {% if LANGUAGE_CODE == 'en' %}
                selected
                {% endif %}
            >{% trans "영어로 변경" %}</option>
            <option value="ko"
                {% if LANGUAGE_CODE == 'ko' %}
                selected
                {% endif %}
            >{% trans "한국어로 변경" %}</option>
        </select>
    </div>
</footer>

templates/partial/message.html
{% if messages %}
<ul class="message absolute top-0 left-0 text-white w-full flex justify-center z-10">
    {% for message in messages %}
    <li class="{% if message.tags %}{{ message.tags }}{% endif %} px-20 py-3 text-sm rounded-full">{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

templates/partial/nav.html
{% load static %}

<div>
    <ul class="flex font-bold text-sm h-20">
        {% if user.is_authenticated %}
            {% if request.session.is_hosting %}
            <li class="nav_link hover:border-red-500"><a href="{% url 'users:is-hosting' %}">Stop hosting</a></li>
            <li class="nav_link hover:border-red-500"><a href="{% url 'rooms:add' %}">Create Room</a></li>
            {% else %}
            <li class="nav_link hover:border-red-500"><a href="{% url 'users:is-hosting' %}">Start hosting</a></li>
        {% endif %}
        <li class="nav_link hover:border-red-500"><a href="{% url 'users:reservations' %}">Reservations</a></li>
        <li class="nav_link hover:border-red-500"><a href="{% url 'lists:detail' %}">Favs ({% if not user.list.room.count %}0{% else %}{{user.list.room.count}}{% endif %})</a></li>
        <li class="nav_link hover:border-red-500"><a href="{{user.get_absolute_url}}">Profile</a></li>
        <li class="nav_link hover:border-red-500"><a href="{% url "users:logout" %}">Log Out</a></li>
        {% else %}
        <li class="nav_link hover:border-red-500"><a href="{% url "users:login" %}">Log In</a></li>
        <li class="nav_link hover:border-red-500"><a href="{% url "users:signup" %}">Sign Up</a></li>
        {% endif %}
    </ul>
</div>

templates/partial/social_login.html
<div class="flex flex-col">
    <a class="btn border border-black bg-white text-black" href="{% url "users:github-login" %}">
        <i class="fab fa-github-alt fa-lg text-black mr-3"></i>
        <span class="font-semibold">Continue with Github</span>
    </a>
    <a class="btn border border-yellow-400 bg-yellow-400 text-yellow-900" href="{% url "users:kakao-login" %}">
        <i class="fas fa-comment fa-lg mr-3 text-yellow-900"></i>
        <span class="font-semibold">Continue with Kakao</span>
    </a>
</div>